kumuluzee:
  name: processing
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  discovery:
    etcd:
      hosts: http://192.168.2.195:2379

  streaming:
    kafka:
      consumer:
        bootstrap-servers: moped-01.srvs.cloudkafka.com:9094
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        security-protocol: SASL_SSL
        group-id: yu0eoldf-consumer
        sasl-jaas-config: org.apache.kafka.common.security.scram.ScramLoginModule required username="yu0eoldf" password="9WRzwOeKUMyro14oenmH_tanFVlrwEFn";
        sasl-mechanism: SCRAM-SHA-256
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        session-timeout-ms: 30000

app-properties:
  external-services:
    enabled: true
  amazon:
    access-key: AKIAYB5TCTPQRLLJJ2Z2
    secret-key: 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